[package]
name = "kovi-check-long"
version = "0.1.0"
edition = "2021"

[dependencies]
check-alllong = { version = "0.1.0", path = "plugins/check-alllong" }
kovi = "0.9.0"

[workspace]

[workspace.dependencies]
kovi = "0.9.0"
